[2023-11-29T10:48:47.070+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: catchup.Bash_2 scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2023-11-29T10:48:47.611+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: catchup.Bash_2 scheduled__2023-11-28T00:00:00+00:00 [queued]>
[2023-11-29T10:48:49.184+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 3
[2023-11-29T10:48:55.813+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): Bash_2> on 2023-11-28 00:00:00+00:00
[2023-11-29T10:48:56.419+0000] {standard_task_runner.py:57} INFO - Started process 684 to run task
[2023-11-29T10:48:56.704+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'catchup', 'Bash_2', 'scheduled__2023-11-28T00:00:00+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/catchup.py', '--cfg-path', '/tmp/tmpgnmvcok8']
[2023-11-29T10:48:57.170+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask Bash_2
[2023-11-29T10:49:05.664+0000] {task_command.py:416} INFO - Running <TaskInstance: catchup.Bash_2 scheduled__2023-11-28T00:00:00+00:00 [running]> on host a89a99bc45b2
[2023-11-29T10:49:33.662+0000] {taskinstance.py:1662} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Dashrath' AIRFLOW_CTX_DAG_ID='catchup' AIRFLOW_CTX_TASK_ID='Bash_2' AIRFLOW_CTX_EXECUTION_DATE='2023-11-28T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-11-28T00:00:00+00:00'
[2023-11-29T10:49:34.066+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2023-11-29T10:49:34.067+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'echo this is second task']
[2023-11-29T10:49:35.821+0000] {subprocess.py:86} INFO - Output:
[2023-11-29T10:49:38.745+0000] {subprocess.py:93} INFO - this is second task
[2023-11-29T10:49:39.214+0000] {subprocess.py:97} INFO - Command exited with return code 0
[2023-11-29T10:49:48.226+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=catchup, task_id=Bash_2, execution_date=20231128T000000, start_date=20231129T104847, end_date=20231129T104948
[2023-11-29T10:49:52.240+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2023-11-29T10:49:53.876+0000] {taskinstance.py:2778} INFO - 0 downstream tasks scheduled from follow-on schedule check
